language: "en"

pipeline: "pretrained_embeddings_spacy"

policies: 
  - name: 'KerasPolicy'
  - name: "FallbackPolicy"
    nlu_threshold: 0.90						#Min confidence needed to accept an NLU prediction
    core_threshold: 0.90						#Min confidence needed to accept an action prediction from Rasa Core
    fallback_action_name: 'action_hello_world'		#Name of the fallback action to be called if the confidence of intent or action is below the respective threshold
